### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by nadiashomali**

### CODE REVIEW

**Comment by nadiashomali** [comment]
I am testing to see how my contributions may show from the LFX

**Comment by nadiashomali** [comment]
Testing the workflow only

**Comment by hodoulp** [comment]
Hi @nadiashomali Welcome to the OpenColorIO project.

When you commit a change, you need to add your signature (i.e. something like `Signed-off-by: Author Name <authoremail@example.com>`. An easy way is to use the `-s` argument for the `git commit`.

Look at the link below to have more details:
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1613/checks?check_run_id=5516708742

I would suggest to amend you the commit if you know (and are comfortable) to do it -- or -- close the PR to create a new one (i.e. new branch, make your change, and then `git commit -sam "a description"`).

**Comment by hodoulp** [comment]
Hi @nadiashomali Do you still want to complete the pull request or can we close it?
Please let us know if you still have questions.

**Pull request closed without merging**
