### PR TITLE
Adds Natron description in compatible_software.rst

### PR DESCRIPTION
**Pull request by Shrinks99**
Signed-off-by: Henry Wilkinson <henry@wilkinson.graphics>

Natron didn't have a description in the documentation before, now it does!

This is a very minor documentation change and I didn't follow the branch naming structure as outlined [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/CONTRIBUTING.md#development-and-pull-requests)... sorry.  Should I ever make more involved PRs to OCIO and not just change things in the GitHub web editor I will definitely follow that.

### CODE REVIEW

**Comment by hodoulp** [comment]
@Shrinks99 your DCO failed. Click on `details` to have info on how to fix that.

**Comment by Shrinks99** [comment]
@hodoulp Apologies, never used the DCO feature before!  I've tried to make it work to the best of my abilities but the bot still says it's failed.

**Comment by hodoulp** [comment]
When committing some changes, the pull request description as well as all the commit descriptions must contain a signature. For example: `Signed-off-by: Patrick Hodoul <Patrick.Hodoul@autodesk.com>`. Using command line, the command is `commit -sam "some explanation"` where the `s` is the automatic sign-off.

However using the GitHub interface to do the changes and the pull request does not add the sign-off.

@jmertic Now that the commits are not signed, how could we help @Shrinks99 ?

**Comment by lgritz** [comment]
On his end, the author can `git rebase -i HEAD~N` where N is the number of commits. When the editor comes up showing the list of commits, for each one change "pick" to "r". When you exit the editor, it will then cycle through each commit, allowing you to edit the commit message, and you can add the Signed-off-by line.

**Comment by Shrinks99** [comment]
After trying to struggle my way through this (looks like I still have a lot to learn about rebasing!) I attempted to fix this with a new [PR with fresh commits that include the correct DCO information](https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1170) but the bot _still didn't like that_.  I've closed that PR so things don't get messier than they already are.

At this point I feel like this is too much of a hassle for such a minor one-line documentation addition.  Feel free to copy what I have submitted here and add it yourselves if you deem it valuable. :)

**Comment by michdolan** [comment]
Seems like an conflict between the ICLA and the DCO. It may not like the private GH email address. I think if the ICLA and the DCO were updated with your actual email address this would be resolved.

**Comment by jmertic** [comment]
@Shrinks99 These two commands should rebase the commits and fix the signoffs...

```
git rebase -i HEAD~6 --signoff
git push --force-with-lease origin patch-2
```

**Comment by Shrinks99** [comment]
Alright well I've taken some time to resolve my frustrations with vim and rebased everything into one nice commit with a DCO, neat!  Thanks @lgritz and @jmertic for the quick tutorial, unfortunately it seems the bot is still unhappy. :(

I checked the CLA but couldn't find anywhere in there that asked for my email?

**Comment by hodoulp** [comment]
`Commit sha: ecaf395, Author: Henry Wilkinson, Committer: Henry Wilkinson; Expected "Henry Wilkinson 5672810+Shrinks99@users.noreply.github.com", but got "Henry Wilkinson henry@wilkinson.graphics".`

That could be related to your GitHub account where your 'official' email is private so GitHub generates that kind of email i.e. `5672810+Shrinks99@users.noreply.github.com`.

In your GitHub account, you can navigate to `settings`, `email` and then look at `primary email`.

**Comment by Shrinks99** [comment]
Fixed GitHub email!  You may have to tell the bot to check again?

**Comment by hodoulp** [comment]
@Shrinks99 Not sure I have the answer, but I would suggest you to push something harmless or redo the 'rebase' & 'push' as described by @jmertic.

**Comment by Shrinks99** [comment]
Success!  The bot is happy!

It was not a problem with GitHub email settings, my actual git configuration email was set incorrectly and [that appears to be what the DCO bot looks at and compares against](https://github.com/probot/dco/issues/39#issuecomment-332911741).  Thank you all again for taking the time to help me sort this out, next time I make a small docs change I'm sure it will be much less of a hassle for all involved :)

**Review by hodoulp — APPROVED** [review]

**Review by doug-walker — APPROVED** [review]

**Pull request merged**
