### PR TITLE
FindPystring: Also find a static pystring lib

### PR DESCRIPTION
**Pull request by autoantwort**
This was at least necessary in https://github.com/microsoft/vcpkg/pull/19272

### CODE REVIEW

**Comment by autoantwort** [comment]
Hm it seems that I can also set the option `pystring_STATIC_LIBRARY` to On. Is there an reason why I have to do it?

**Comment by hodoulp** [comment]
> Hm it seems that I can also set the option pystring_STATIC_LIBRARY to On. Is there an reason why I have to do it?

Discovering a library using the `pkgconfig` mechanism generates this variable. However, the `Findpystring.cmake` did not implement the corresponding code so, the variable is never set. Based on the `pystring` GitHub repo, the `pkgconfig` was never implemented.

**Review by hodoulp — COMMENTED** [review]
The fix is the right one.

Following my comment, could you complete the work by cleaning the file i.e. remove lines 44 to 48, and remove the use of `${_pystring_STATIC}` ?

**Comment by autoantwort** [comment]
Ok done.

**Review by hodoulp — APPROVED** [review]
Thanks @autoantwort for your help.

**Comment by autoantwort** [comment]
Do you know why the pipeline fails? I only see
```
2021-08-05T16:28:52.6201609Z ##[error]The operation was canceled.
```

**Comment by hodoulp** [comment]
@autoantwort here is the link to 'enable' the DCO.

**Comment by hodoulp** [comment]
Friendly reminder that the pull request could be merged next week so, you could use that period to review the changes.

**Comment by autoantwort** [comment]
Do you mean me? Yeah the PR is ready and can be merged

**Comment by hodoulp** [comment]
@autoantwort The rule is to wait for 2 approvals or 2 weeks (without pending discussion and one approval) before merging a pull request. So, I raise the point to the community that the delay ends next week. If there is a second approval before the delay I can merge the pull request sooner.

**Review by michdolan — APPROVED** [review]

**Pull request merged**
