### PR TITLE
Fix Github license detection

### PR DESCRIPTION
**Pull request by jmertic**
Rename LICENSE.md to LICENSE and LICENSE-THIRD-PARTY.md -> THIRD-PARTY.md to get around GitHub license checks not working right.

### CODE REVIEW

**Comment by michdolan** [comment]
Which GitHub license check isn't working with the .md extension?

**Comment by jmertic** [comment]
The one in the bar above the code - see attached...

Screen Shot 2019-10-02 at 12 00 12 AM

**Comment by michdolan** [comment]
Got it, thanks for the clarification. Looking at your fork shows the results of the fix, which is a "BSD-3-Clause" label.

**Comment by hodoulp** [comment]
The merge fails because there are still some LICENSE.md in the code:
```
./docs/CMakeLists.txt:    ${CMAKE_SOURCE_DIR}/LICENSE.md
./docs/License.rst:.. include:: LICENSE.md
```

**Pull request merged**
