### PR TITLE
Add Python 3.12 wheels

### PR DESCRIPTION
**Pull request by remia**
This adds support for Python 3.12 wheels. I'm considering removing Python 3.7 wheel generation given that this version is now EOL and studios relying on it would most likely not get it through PyPI, any thoughts?

### CODE REVIEW

**Review by doug-walker — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
@remia I would recommend continuing to ship wheels for 3.7 for a little while if it doesn't add too much work/annoyances.

**Comment by remia** [comment]
Sure @JeanChristopheMorinPerso, I don't remember any issues beyond the growing number of Python version we generate wheels for, let's leave it then.

**Comment by doug-walker** [comment]
Remi, are you expecting the changes in here will fix the Wheel Actions failure?

**Comment by remia** [comment]
> Remi, are you expecting the changes in here will fix the Wheel Actions failure?

Yes, but the rebase against main did bring new errors related to yaml-cpp which need fixing before merging.

**Comment by remia** [comment]
I believe the issue was that the Python setup.py currently calls CMake configure multiple times (used to get the version of the project) with conflicting `OCIO_INSTALL_EXT_PACKAGES` flags (no flag to extract the version so defaulting to MISSING then ALL for the actual build). Findyaml-cpp was creating a yaml-cpp::yaml-cpp target even if the package was not found which prevented correct installation of the package during the build.

I also took the liberty to have Installyaml-cpp directly create a yaml-cpp::yaml-cpp target for simplicity.

@tobim are you fine with those changes following your previous PR?

**Comment by tobim** [comment]
Of course, don't worry about me.

**Comment by remia** [comment]
I moved the yaml-cpp related fixes to #1907 so this PR should only be merged after it is merged.

**Comment by remia** [comment]
Ready for merge again now that #1907 was merged (pending review).

**Review by carolalynn22 — APPROVED** [review]
Approving to get this in to 2.3.1

**Comment by KelSolaar** [comment]
Sorry, haven't had time to look at this one like I said I would! Lot of work...

**Pull request merged**
