### PR TITLE
Fix CI warnings / deprecations

### PR DESCRIPTION
**Pull request by remia**
This fix various warnings in GitHub Actions related to the use of deprecated actions, as well as bumping the macOS runners to avoid the [brownout](https://github.com/actions/runner-images/issues/5583) issue we are currently facing.

### CODE REVIEW

**Review by michdolan — APPROVED** [review]
Thanks @remia !

**Review by doug-walker — APPROVED** [review]

**Comment by remia** [comment]
@michdolan Could you please update the required checks list to change macOS 10.15 to macOS 11? Thanks!

**Comment by remia** [comment]
Reminder, this need to merged if we want to avoid MacOS CI issues.

**Comment by remia** [comment]
Any news on merging this?

**Comment by remia** [comment]
Thanks @doug-walker !

**Pull request merged**
