### PR TITLE
Website build process minor readme updates

### PR DESCRIPTION
**Pull request by Shrinks99**
Should be blocked by [`89b8d1a` (#1330)](https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1330/commits/89b8d1a3df95d54f99828b95ff6d8b73008ddded) until it is merged so that any other issues that we run into can be resolved and made a part of the build process.

- Updates build process with minifiy enabled
- Updates sizzle reel link at the request of @doug-walker 

Signed-off-by: Henry Wilkinson <henry@wilkinson.graphics>

### CODE REVIEW

**Review by michdolan — APPROVED** [review]

**Comment by hodoulp** [comment]
As @michdolan approved the changes, @Shrinks99 you can now make it a pull request (instead of a draft), so we can merge it next week.

**Comment by Shrinks99** [comment]
I could do that if you want to get it approved and in but my intention with this PR was to not have it merged until the website is actually updated to resolve any errors in the build process (as I've already found one).  Hopefully no more will come about before 89b8d1a (#1330) is approved but if they do I planned to include them in here and that's why it's still a draft.

Happy to defer to what you think is best if you want to push this through though @hodoulp.

**Comment by doug-walker** [comment]
I think you have a good plan @Shrinks99 , we will merge 1330 first.

**Comment by hodoulp** [comment]
PR1330 is already merged. I'm waiting a success build to merge this one.

**Review by hodoulp — APPROVED** [review]

**Pull request merged**
