### PR TITLE
Adsk Contrib - Fix half-domain Lut1D issue for values above HALF_MAX

### PR DESCRIPTION
**Pull request by doug-walker**
This fixes an issue where float values greater than HALF_MAX but which don't round to Infinity (in other words, values between 65505 and 65519) were returning NaN. (This did not affect the GPU, only CPU.)

If this issue was encountered when inverting a normal domain Lut1D, and a work-around is needed before receiving this fix, turn off the OPTIMIZATION_LUT_INV_FAST optimization flag. For example, to use the default settings but turn off this flag, set the environment variable as follows:
export OCIO_OPTIMIZATION_FLAGS=230440899

### CODE REVIEW

**Comment by hodoulp** [comment]
Friendly reminder that the pull request can now be merged this week as it's now more than 2 weeks old.

**Review by remia — APPROVED** [review]
Sorry for the late review @doug-walker.

> If this issue was encountered when inverting a normal domain Lut1D

Just checking, did you mean half-domain Lut1D?

I reproduced the bug in `ocioconvert` and Nuke 13 by applying the LUT you use in your test to an EXR with a value > 65504 and can confirm the fix works by making the `fraction` a `NaN` that is then converted to 0 instead of producing an `inf` before.

**Comment by doug-walker** [comment]
@remia , yes, the description is correct, I really did mean "normal domain Lut1D".  When the "fast inverse" optimization option is enabled, when a normal domain Lut1D is inverted it often becomes a forward evaluation in a half-domain Lut1D (this happens when the range of the LUT exceeds [0,1]).  That was the scenario involved in the original bug report.

**Review by hodoulp — APPROVED** [review]
As the PR is already more than two-weeks old, I approve it.

**Pull request merged**
