### PR TITLE
Add VFX 2024 to CI

### PR DESCRIPTION
**Pull request by remia**
Adding VFX 2024 Docker images from @jfpanisset to the CI workflow.

Also proposing a small bump in CMake minimum version to fix a warning appearing when using `FetchContent_Populate` on latest CMake releases.

### CODE REVIEW

**Review by doug-walker — APPROVED** [review]

**Comment by doug-walker** [comment]
I've updated the build matrix spreadsheet to reflect these changes (scroll down):
https://docs.google.com/spreadsheets/d/1Iw5uRw6voB54wFpkSSOGrcAXkciZfx9nlBSVHz6N4P8/edit?usp=sharing

**Review by zachlewis — APPROVED** [review]

**Comment by doug-walker** [comment]
Per the discussion at the TSC meeting today, we will go ahead and merge this one. The failing CI checks are not relevant.

**Comment by remia** [comment]
@doug-walker I forgot to mention that the names of the Linux jobs got updated so we will need to update Github required check list probably.

**Comment by doug-walker** [comment]
It should be working (?), I updated the job names after I merged this. Please let me know if it needs more adjustment.

**Comment by remia** [comment]
Thanks @doug-walker, my bad, I was looking at a PR where the CI workflow was not triggered since the merge so it was missing required checks where the names changed, as expected.

**Pull request merged**
