### PR TITLE
CMake and ext package upgrades

### PR DESCRIPTION
**Pull request by michdolan**
A variety of updates to ext package versions and CMake find modules:

- Upgrade to CMake 3.12
- Favor third-party CMake configs for finding packages
- Adopt standard CMake <package>_ROOT variables for overriding package locations
- Upgrade Half version to match VFX Reference Platform CY2020
- Upgrade other packages to take advantage of upstream CMake upgrades and configs
- Match find module variable namespace to target name, and target names to third-party CMake configs
- Move ext find package calls to project root to guarantee imported targets are global

See #1016 for discussion around other changes. This branch contains my commits cherry-picked from that branch. @scoopxyz will submit a follow-up PR with his changes.

Signed-off-by: Michael Dolan <michdolan@gmail.com>

### CODE REVIEW

**Comment by michdolan** [comment]
NOTE: I did some refactoring of the OpenGL and headless rendering messaging section of the main CMakeLists.txt file. It will now not check or warn about headless rendering unless GPU rendering can be enabled. Worth a sanity check from @hodoulp and @ChinYing-Li . Thanks!

**Comment by michdolan** [comment]
Closing and reopening to re-trigger CI

**Comment by hodoulp** [comment]
@michdolan Without the fixes from @scoopxyz any builds with python 2.x fail!

**Comment by michdolan** [comment]
Our CI builds and tests Python 2 and 3 and everything built and passed Python tests. Where are you seeing a build failure? 

The intent is for Sean to submit a follow-up PR, which in a worst case scenario could be merged immediately after this PR. We had a lot of issues around DCO failing when collaborating on the previous PR.

**Comment by michdolan** [comment]
Here are the Python 2.7 builds for reference:

**Linux:**
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1061/checks?check_run_id=865152350
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1061/checks?check_run_id=865152422

**macOS:**
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1061/checks?check_run_id=865152265

**Windows:**
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1061/checks?check_run_id=865152497

**Comment by hodoulp** [comment]
Here is my result (macOS, python 2.7.16):

```
git fetch origin pull/1061/head:pr-1061
git checkout pr-1061
rm -rf *
cmake ../.
```

```
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found PythonLibs: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-- Found pybind11: /usr/local/include (found suitable version "2.5.0", minimum required is "2.4.3") 

-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.16", minimum required is "2.7") 
CMake Error at /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is at
  least version "2.7")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/bindings/python/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by michdolan** [comment]
try adding to cmake call:
`-DPYTHON_EXECUTABLE=$(which python)`

**Comment by michdolan** [comment]
We _can_ try to merge @scoopxyz commits into this PR again if needed. It should be clean now since the branch is new. It gets complicated when needing to rebase to amend commit messages when there are multiple contributors.

**Comment by scoopxyz** [comment]
Yeah, quickly finding how nasty it gets if we don't validate DCO before creating any PRs... maybe there is a post-commit hook we could enforce it with?

**Comment by hodoulp** [comment]
> try adding to cmake call:
> `-DPYTHON_EXECUTABLE=$(which python)`

It does not work.

> Yeah, quickly finding how nasty it gets if we don't validate DCO before creating any PRs... 

Something to talk at the TSC. Many contributors (first contribution) get stuck with their pull request because of that 'double' validation i.e. always one missing.

**Comment by michdolan** [comment]
@scoopxyz if you make a PR against this new branch we can give it a whirl again.

**Comment by zachlewis** [comment]
@hodoulp try additionally setting 'PYTHON_INCLUDE_DIRS', e.g:
`-DPYTHON_INCLUDE_DIRS=$(python -c "from distutils import sysconfig; print(sysconfig.get_python_inc())"`

**Pull request merged**
