### PR TITLE
Adsk contrib - Fix issue with minizip build

### PR DESCRIPTION
**Pull request by cedrik-fuoco-adsk**
This is the PR for [Impossible to build against system/external minizip-ng](https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1718).

I removed the minizip-ng subfolder part when including minizip-ng's headers. This fixes the issue with external builds that don't use that subfolder.

For internal builds, a subfolder is created like the other modules that OCIO is able to download and install manually.

I've decided that having Findminizip-ng.cmake and Findminizip.cmake is less confusing than having only a Findminizip.cmake since "minizip" is not the actual name of the library (minizip-ng without MZ_COMPAT=ON).

Therefore, the build system does the following:
1) Search for minizip-ng (libminizip-ng) (without MZ_COMPAT=ON)
2) If minizip-ng is not found,  Search minizip-ng with MZ_COMPAT=ON (which is libminizip).
3) If steps 1 and 2 are not found, download and install minizip-ng with MZ_COMPAT=OFF. 
It is set as OFF because we don't need the compatibility part. We are using the "new" API from minizip-ng.

### CODE REVIEW

**Comment by cedrik-fuoco-adsk** [comment]
Note that the analysis workflow is failing, but it was failing before already. The PR does not introduce any new problems with the analysis workflow.

**Comment by doug-walker** [comment]
@remia @michdolan , could one of you review this?  Merging this would simplify an upcoming PR for us.  TIA!

**Comment by remia** [comment]
Looks good to me, thanks for updating the Analysis workflow! One thing I noticed while testing on macOS, the build with install ALL externals deps works perfectly but when using the minizip-ng from brew, it seems the `mz_strm_zlib.h` header is missing from `/usr/local/include` (all the other minizip include are present though). Does anyone else have this issue?

**Comment by cedrik-fuoco-adsk** [comment]
> Looks good to me, thanks for updating the Analysis workflow! One thing I noticed while testing on macOS, the build with install ALL externals deps works perfectly but when using the minizip-ng from brew, it seems the `mz_strm_zlib.h` header is missing from `/usr/local/include` (all the other minizip include are present though). Does anyone else have this issue?

The minizip-ng packages available through brew do not have a dependency on _zlib_. That tells me that particular minizip-ng wasn't built with _zlib_ compression activated. Based on the dependencies list, it was built with _xz_ and _zstd_ compression activated - which corresponds with the missing `mz_strm_zlib.h`.

**Comment by doug-walker** [comment]
Thanks for the review Remi!  Regarding the Brew issue, based on Cedrik's reply, it sounds like the Brew minizip-ng cannot be used with OCIO since it was not compiled with zlib support activated.  In any case, I think we could merge this one now to unblock Cedrik's other PR.  We could come back to the Brew issue later, if that's ok with you.

**Review by remia — APPROVED** [review]

**Comment by remia** [comment]
Thanks @cedrik-fuoco-adsk yeah that make sense, I guess I'm surprised that zlib is not used it seemed like an obvious choice (to my naive eyes). Agree @doug-walker sorry for dragging this PR!

**Comment by doug-walker** [comment]
Don't worry Remi, you did not drag the PR.  You raised an excellent point about Brew.  And in fact you sped up the PR by reviewing it, thank you!!

**Pull request merged**
