### PR TITLE
Added TSC meeting notes

### PR DESCRIPTION
**Pull request by Shootfast**

### CODE REVIEW

**Comment by hodoulp** [comment]
@Shootfast You forgot to `signoff` the commit.

**Comment by Shootfast** [comment]
Yeah I saw. I just used the built-in editor in github.com to submit, so I was hoping it would do all that jazz automatically.

**Comment by hodoulp** [comment]
@jpalmerLinuxFoundation What does it mean? 
The previous behavior was that a branch could be updated even if DCO failed and without approvers e.g. tested on #843

**Comment by jpalmerLinuxFoundation** [comment]
@hodoulp, Sorry, I'm not sure I have the answer. I'm just trying to make sure that EasyCLA is running on any PRs to OpenColorIO

**Comment by hodoulp** [comment]
@jpalmerLinuxFoundation Below is the message when I try to update the pull request:
```
Update branch attempt failed
Couldn't update "meeting-notes": Required status check "DCO" is expected. At least 2 approving reviews are required by reviewers with write access.
```

**Pull request closed without merging**
