### PR TITLE
Issue #1874 Cast to unsigned char for isspace.

### PR DESCRIPTION
**Pull request by pennelee**
Fix for: https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1874

Cast to unsigned char before using std:isspace().

From cppreference:

Like all other functions from cctype, the behavior of std::isspace is undefined if the argument's value is neither representable as unsigned char nor equal to EOF. To use these functions safely with plain chars (or signed chars), the argument should first be converted to unsigned char

### CODE REVIEW

**Comment by doug-walker** [comment]
Thanks for this fix @pennelee.  Please let us know if you have problems getting the CLA signed.

Would you please add a unit test along the lines of what Remi suggested?

**Comment by pennelee** [comment]
Hi @doug-walker , 
Yes, Sean is working on the CLA for the company, hope it will be sorted out soon.

Sure I can add the unit test Remi suggested, I had it locally but didn't push the change.

**Comment by pennelee** [comment]
Hi @doug-walker,
I have added the unit test and also CLA is now signed, and I am approved as contributor.

**Comment by doug-walker** [comment]
Thanks for getting the CLA signed @pennelee.  Could you add the comment I suggested to the unit test please?

**Comment by pennelee** [comment]
I'm sorry @doug-walker , which comment do you refer to?

**Review by doug-walker — CHANGES_REQUESTED** [review]

**Comment by doug-walker** [comment]
Apologies @pennelee, I had made a comment but it had not been submitted.  You should see it now I think.

**Comment by pennelee** [comment]
@doug-walker Thanks Doug I have updated with the unit test comment.

**Review by doug-walker — APPROVED** [review]
Thanks @pennelee !

**Comment by pennelee** [comment]
Hi @remia , 
Could you please help to review this PR when you have time?  Thank you!

**Review by remia — APPROVED** [review]
Looks good to me, thanks for the contribution @pennelee !

**Pull request merged**
