### PR TITLE
Updates website with rebuilt version

### PR DESCRIPTION
**Pull request by Shrinks99**
- Rebuilt with `hugo -D --minify --themesDir ../..` as per the new docs
- Added .gitignore file for .DS_Store files in the `gh-pages` branch

This build notably still includes some un-used template blog posts which are also present in the live build as well as changes that I did not make like removal of old logos, an image from Spiderverse, and updates to application icons.  When I built the website on my local machine previously everything worked fine, assuming nothing has changed with the website config since it was last built (pre-build instructions) this should be good to go.  I recognize it is hard to review these types of changes.

EDIT: Fixed DCO because I messed it up again but hey, what else is new.

### CODE REVIEW

**Comment by doug-walker** [comment]
Hi @Shrinks99, thanks for this.  @carolalynn22 would be the best person to review this one.

As long as you're building/testing the site, bonus points for updating index.html to switch out the old sizzle reel:
www.youtube.com/embed/8z61RZhvKQ8
for our new one:
www.youtube.com/embed/sa7WqKxDRKY

Thanks again!

**Comment by Shrinks99** [comment]
> As long as you're building/testing the site, bonus points for updating index.html to switch out the old sizzle reel:
> [www.youtube.com/embed/8z61RZhvKQ8](http://www.youtube.com/embed/8z61RZhvKQ8)
> for our new one:
> [www.youtube.com/embed/sa7WqKxDRKY](http://www.youtube.com/embed/sa7WqKxDRKY)

I've got no problem updating this, can add and then do another PR against the main branch for the website source?

**Comment by hodoulp** [comment]
This pull request is now blocking another smaller one and both will greatly improve the overhall documentation quality. @carolalynn22, could you review the pull request when you have some time?

**Review by carolalynn22 — APPROVED** [review]
Sorry for the delay, looks great to me, thank you for the contribution @Shrinks99 !

**Review by doug-walker — APPROVED** [review]

**Review by hodoulp — APPROVED** [review]

**Pull request merged**
