### PR TITLE
Remove fnordware plugins

### PR DESCRIPTION
**Pull request by kingsawyer**
Photoshop and After Effects now provide native OCIO support. These plugins will be preserved in a separate repo. Thank you Brendan for your great work on these plugins that helped bridge the gap to native support!

### CODE REVIEW

**Comment by kingsawyer** [comment]
Thank you @fnordware for these plugins

**Comment by fnordware** [comment]
Do it!

**Comment by kingsawyer** [comment]
@doug-walker @carolalynn

**Comment by fnordware** [comment]
Yep, still available for download on [fnord.com](fnord.com) and I plan to keep them up there for people with old After Effects project, etc.

**Comment by fnordware** [comment]
And yes, I'll update that page to point to the new repo once I set it up.

**Comment by carolalynn** [comment]
Perfect, thanks!

**Review by doug-walker — APPROVED** [review]

**Comment by kingsawyer** [comment]
@carolalynn ping

**Review by carolalynn — APPROVED** [review]
Sorry, I thought I had approved this!

**Comment by tempuserr** [comment]
Not everyone want to fight with new AE bugs and use the latest version.
Please keep this AEX plugin repo updated if possible.

**Comment by fnordware** [comment]
Don't worry, I've moved the plug-ins to a [new repo](https://gitlab.com/fnordware/AdobeOCIO) and posted new builds on [fnord.com](http://fnord.com). Will keep updating periodically.

**Pull request merged**
