### PR TITLE
Adsk Contrib - Move AppHelpers to core

### PR DESCRIPTION
**Pull request by BernardLefebvre**
Following up on the request from a recent TSC meeting, this PR moves the App Helpers code into the core library.  This adds no new third-party dependencies.  (The App Helpers code is intended to simplify the work of integrating OCIO into a real-world DCC application.)  Also, following up on another suggestion, the ViewingPipeline class was renamed LegacyViewingPipeline.

Signed-off-by: Bernard Lefebvre <bernard.lefebvre@autodesk.com>

### CODE REVIEW

**Review by michdolan — COMMENTED** [review]
Looks good! Only comment is the Python binding source will need some adjustments (adding DOC calls) following the recently merged #1197,  and you will need to re-freeze the RST.

**Comment by michdolan** [comment]
@BernardLefebvre if it's helpful I could submit a PR to your branch to update the Python bindings based on the recent work I did. I could do so fairly quickly so let me know. I know you have other important tasks on your plate, so happy to help if needed.

**Comment by BernardLefebvre** [comment]
Thank you @michdolan that will be very helpful. I tried the suugested workflow on PR #1221. I first resolved the conflict pushed a commit and then added -DOCIO_BUILD_FROZEN_DOCS=ON before a build but that did not do anything.

For this PR, there is a follow-up commit coming that implements #1222. I suggest that I first do that commit (it could takes a few days), then I'll request your help.

**Comment by michdolan** [comment]
Did you also specify `-DOCIO_BUILD_DOCS=ON`? They should really be linked so that you only need to specify the one, but currently you have to have both.

**Comment by BernardLefebvre** [comment]
You're right I did not turn the other flag on. Now I need to upgrade to Python 3. I was surprised the other PR did build but this one did fail.

**Comment by hodoulp** [comment]
As usual this is a notice that we will merge this week, if there are no more discussions on the pull request.

**Comment by doug-walker** [comment]
Hi all, with the latest commits, this PR now implements the proposals in issue #1222.  Please take a look at our latest work and provide your review.  Thanks!

**Review by hodoulp — APPROVED** [review]

**Review by doug-walker — APPROVED** [review]

**Comment by doug-walker** [comment]
Merging this per discussion at TSC meeting today.

**Pull request merged**
