### PR TITLE
Adsk Contrib - Add the RPATH support

### PR DESCRIPTION
**Pull request by hodoulp**
Signed-off-by: Patrick Hodoul <Patrick.Hodoul@autodesk.com>

The pull request adds the `RPATH` to correctly find & load the library.

The details are:
- `cmake` -> the RPATH is the compilation directory build.
- `cmake install` -> the RPATH is a relative path based on the installation directory structure i.e. usual value for *nix platforms.

Refer to #1327 for details.

### CODE REVIEW

**Review by michdolan — APPROVED** [review]

**Comment by remia** [comment]
Works fine on macOS, thanks @hodoulp.

The generated python bindings will still fallback to a system wide location as the relatives path will not work so user might still want to manually edit these install RPATH. But that's probably a too specific specific situation to do anything generic about it, just need to be aware of it I guess.

**Comment by hodoulp** [comment]
@remia, if the way ocio installs the Python binding dynamic library is the usual installation directory structure for *nix platforms (i.e. `lib/pythonX.Y/site-packages` ), I can definitively add `@loader_path/../..` to the rpath.

**Comment by remia** [comment]
Thanks @hodoulp, great to use `set_target_properties` to limit the scope.

It works for me, and I don't see reason not to do it so far :)

**Comment by hodoulp** [comment]
Tested on:
- ubuntu 20:4, cmake 3.16, gcc 9.3
- macOS 10.15, cmake 3.18, clang 12.0

**Review by michdolan — APPROVED** [review]

**Comment by hodoulp** [comment]
Friendly reminder that the pull request can now be merged next week.

**Review by doug-walker — APPROVED** [review]

**Pull request merged**
