### PR TITLE
Update supported_apps.yml for AE and PS

### PR DESCRIPTION
**Pull request by kingsawyer**
Update public page for After Effects and Photoshop support

### CODE REVIEW

**Comment by kingsawyer** [comment]
@fnordware @doug-walker

**Review by carolalynn — APPROVED** [review]
Looks good, thanks!

**Comment by kingsawyer** [comment]
Hugo is pretty cool. Website was easy to build and test.

**Comment by carolalynn** [comment]
Glad to hear it - we appreciate the feedback! Not many folks outside core OCIO devs have tried it :)

**Review by doug-walker — APPROVED** [review]

**Pull request merged**
