### PR TITLE
Update aces_1.0.3.rst

### PR DESCRIPTION
**Pull request by chrisbrejon**
Signed-off-by: chrisbrejon <chrisbrejon@gmail.com>

### CODE REVIEW

**Comment by chrisbrejon** [comment]
Hello, sorry I got busy this week and could not work as much as I could.
I have done a quick mockup to discuss the aces documentations in the ocio docs.
Happy to discuss this on Friday. Thanks a lot !
aces_documentation

**Review by doug-walker — APPROVED** [review]

**Comment by chrisbrejon** [comment]
From meeting of 2020/09/11, it has been discussed that we could probably for option number 2 : "no versioning" and that under the aces header, we would link to the different configurations.
It has also been talked about linking directly to the GitHub repository rather than copying/pasting the text. Here are the url we could link to : 
https://github.com/imageworks/OpenColorIO-Configs/tree/master/aces_1.0.3
https://github.com/colour-science/OpenColorIO-Configs/releases

**Comment by hodoulp** [comment]
@chrisbrejon Does it mean that you want to update this pull request?
If not I can approve and merge it. Let me know.

**Comment by chrisbrejon** [comment]
I'd rather go with a new PR if this is fine with you. Probably next week. If we could merge meanwhile... Thanks.

**Review by hodoulp — APPROVED** [review]

**Pull request merged**
