### PR TITLE
Removes commented out OCIO_BUILD_PYTHON

### LINKED ISSUE #1050: Python tests always build even if OCIO_BUILD_PYTHON is off
#1025 updated the python tests, but forgot to un-comment the `OCIO_BUILD_PYTHON` test in cmake [that protected it](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/tests/CMakeLists.txt#L23), meaning they are always on now and you can't build OCIO without python.

### PR DESCRIPTION
**Pull request by sobotka**
Fixes #1050.

### CODE REVIEW

**Comment by hodoulp** [comment]
Hi @sobotka 
You forgot to sign the commit i.e. `git commit -sam "blabla"`. The DCO details explain how to proceed.

**Comment by sobotka** [comment]
Ok, I _think_ I have jumped through all successful hoops to have the single character patch accepted. Fingers crossed.

Let me know.

**Comment by hodoulp** [comment]
@sobotka no success because of the missing sign-off, perhaps @jmertic or @michdolan could help.

**Comment by jmertic** [comment]
Details on the DCO at https://github.com/AcademySoftwareFoundation/tac/blob/master/process/contributing.md#contribution-sign-off. 

Looks like you can fix this locally by...

```
git commit --amend --signoff
git push --force-with-lease origin patch-3
```

**Comment by sobotka** [comment]
Sorry, I mistook the "sign" to mean GPG signed.

**Pull request merged**
