### PR TITLE
Revert "Document OpenColorIO Development Process"

### PR DESCRIPTION
**Pull request by doug-walker**
Reverts AcademySoftwareFoundation/OpenColorIO#1140

### CODE REVIEW

**Comment by michdolan** [comment]
Instead of reverting this, I propose any suggested changes are presented in a follow up issue or PR. The sections @KelSolaar flagged are present in `CONTRIBUTING.md` even with this reverted, so the policy is present in either case.

**Comment by michdolan** [comment]
@KelSolaar on the question of sharing this document for community input. I raised it for discussion at the last three TSC meetings requesting input and additional reviewers:

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/ASWF/meetings/tsc/2020-09-14.md
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1156/files
(this week's TSC meeting, which I have not submitted minutes for yet)

To be fair though, it was revised quite a bit in the last week from discussion between @doug-walker and I. That discussion primarily led to the removal of some conditions which weren't used in practice. I think this document is still open for discussion and revision though, so by all means let's continue to refine it to get it right.

**Comment by KelSolaar** [comment]
To me, the document is in a state where the larger community should be asked for feedback but not just in TSC, wider, e.g. Slack and Mailing list as not everybody is attending the TSC or reading the notes. If no feedback is given, we can assume it is happy :)

**Comment by michdolan** [comment]
I'm closing this to move discussion to a new issue for further discussion: #1161 

I will invite the community there for additional comment.

**Pull request closed without merging**
