### PR TITLE
Adjusted family definitions in documentation and resolved issue #1223

### PR DESCRIPTION
**Pull request by Ansh-Sarkar**
Signed-off-by: Ansh Sarkar a.k.a Seraphim Coder <anshsarkar18@gmail.com>

### CODE REVIEW

**Comment by doug-walker** [comment]
Hi @Ansh-Sarkar , thanks for the PR but please read the CONTRIBUTING.md file and take note of the section "Contributor License Agreements".
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/CONTRIBUTING.md

There must be a CLA in place before we are able to merge anything from you and your commits must be signed-off.

**Review by doug-walker — CHANGES_REQUESTED** [review]
The contents of the PR look good, we just need the CLA in place.  Thanks!

**Comment by Ansh-Sarkar** [comment]
@doug-walker had signed the CLA. No idea why it's not showing up. Will sign it again.

**Comment by Ansh-Sarkar** [comment]
@doug-walker sorry for the inconvenience but i think the problem is due signing of the commit by a different user id. May I close this pull request and try again ? or should is there any other way ? I have received the confirmation email regarding successful signing of the CLA but it's not getting updated here. Pls guide.

**Comment by doug-walker** [comment]
@Ansh-Sarkar , yes you may certainly close the PR and try again.  Apologies for the hassle and thank you for your contribution.

**Comment by Ansh-Sarkar** [comment]
ok @doug-walker thank you. will follow up with the next PR soon

**Comment by Simran-B** [comment]
> May I close this pull request and try again ? or is there any other way ?

@Ansh-Sarkar It's possible to edit an existing PR on the command line with Git, but it's not straightforward. It involves `rebase` and `push --force` and Git needs to be configured up front if you haven't used it before. It's probably easier to just open a new PR in this case.

**Comment by Ansh-Sarkar** [comment]
@Simran-B thank you for that info. Will experiment with it on a few of my own repos first . If that's the case then it would be really helpful. Thank you once again , will surely try it out.

**Pull request closed without merging**
