### PR TITLE
Adsk Contrib - RB-2.0 release

### PR DESCRIPTION
**Pull request by BernardLefebvre**
Cherry-pick all commits from master to update branch to V2.0 release.

Add UNIFORM_FLOAT3, setStrictParsingEnabled to PyOpenColorIO (#1280) Michael Dolan michdolan@gmail.com 73be29a4bacfd560193514af496c0cab6673f77e

Restructure PyOpenColorIO, complete PyGpuShaderDesc (#1275) Michael Dolan michdolan@gmail.com 081b8de4d2f005b12ef7183d21744c2259bcb0c4

Adsk Contrib - More python tests and bindings fixes (#1274) 574ccd856eba78d493b56b4e63d8beb24ef8fb9b

Adsk Contrib - Avoid NaN values in certain Lut1D arrays (#1272) 50e5d8b37db24c1979c9406476479fa21864e261

Transform Python Binding Fix (#1277) Frankie Eder frankaeder@gmail.com c324ba5438cabf0de777404c1709bd87a6d47491

Use OIIO-provided CMake find module (#1266) Michael Dolan michdolan@gmail.com 8774ebf739b0303850cd85b09eff754653d40154

Fix issue #1262 (#1271)  d51962acf067287ddbafce98028f0a71843989b3

Adsk Contrib - Python repr and LogCameraTransform fixes (#1270)  c033d11ee321c6c9492163868d353ed3db1d066d

Add roles to API and fixes (#1267) 8cf0211c3fe367326e54fdf373d3a6dd0d7d8c42

Adsk Contrib - Shader textures now available via Python (#1268) 711042573275c4080b3445b276e9d64d1de28461
Do not squash to keep list of changes.

Signed-off-by: Bernard Lefebvre <bernard.lefebvre@autodesk.com>

### CODE REVIEW

**Comment by michdolan** [comment]
We need to setup new branch protection for RB-2.x. It's currently following the RV-1.x rules, which is why the required checks are off. I'll update it.

**Comment by michdolan** [comment]
Branch protection updated so all checks are now passing

**Review by michdolan — APPROVED** [review]

**Comment by BernardLefebvre** [comment]
Thank you @michdolan

**Review by hodoulp — APPROVED** [review]

**Comment by BernardLefebvre** [comment]
This is missing 2 commits

**Pull request closed without merging**
