### PR TITLE
Adsk Contrib - Add app. helpers

### PR DESCRIPTION
**Pull request by hodoulp**
Signed-off-by: Patrick Hodoul <Patrick.Hodoul@autodesk.com>

The pull request mainly contains several helpers to ease the build of menu UIs. These helpers are built on top of the OpenColorIO library, and they are all optional but useful for color spaces, (display, view) pairs and color picker menu UIs.

The add of categories (refer to PR #648) to filter color spaces, now enables to build UI menus with a limited set of color spaces. As example, the `ColorSpaceMenuHelper` helps to create the appropriate list of color spaces (i.e. criteria is either a role or a list of categories). On the other hand, the `MixingSlider` helps to have linear or perceptually linear sliders for a color picker UI. And the (display, view) pair helper methods provide convenient way to add or remove a (display, view) pair while managing the active display and view lists.

As usual, lot of unit tests are validating the new feature.

_Note:_ When merged with the (display, view) improvements (refer to PR #939), all the existing command line apps could be refactored to be modernized and become much more appropriate examples to any dev. willing to integrate OCIO in their application.

### CODE REVIEW

**Comment by hodoulp** [comment]
Here is a good example of the benefits having several builds...

**Comment by hodoulp** [comment]
**Note:** The build system reported an error when running unit test binaries built using the dynamic library (i.e That's something between the usual [dll hell](https://en.wikipedia.org/wiki/DLL_Hell) on the Windows platform and CMake on Windows i.e. Linux platforms are all working perfectly). The CI builds never failed because GPU unit tests are not executed and I never noticed the problem because my dev environment adds the path to the dll (i.e. updates `PATH` envvar) outside the make files. After hour of investigations, I found (thanks google) a recommended way to fix the problem. It works well for the newly added unit test around [apphelpers](https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/952/commits/a95c6de788f74492bc2c0efae1ae3f0a3b750850), but it still fails for gpu unit test binary.

Investigations are still ongoing but at least, the CI build is now green.

**Comment by hodoulp** [comment]
Following the two-weeks rule, here is a friendly reminder that the branch can now be merged this week unless there are some comments.

**Comment by doug-walker** [comment]
This has been up for two weeks, given that there has been no feedback, we will go ahead and merge tomorrow.

**Pull request merged**
