### PR TITLE
fix(grammatical): Spelling mistakes

### PR DESCRIPTION
**Pull request by AbhineshJha**
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.

### CODE REVIEW

**Review by doug-walker — APPROVED** [review]
Thank you @AbhineshJha !  Was this done as an ASWF Dev Days project?

**Comment by AbhineshJha** [comment]
nope sir @doug-walker

**Comment by AbhineshJha** [comment]
@remia @cedrik-fuoco-adsk please review my pr sir

**Review by carolalynn22 — APPROVED** [review]
LGTM :) Thanks for the PR!

**Comment by AbhineshJha** [comment]
Can u merge this.. @carolalynn22

**Pull request merged**
