### PR TITLE
initial v2 doc restructure

### PR DESCRIPTION
**Pull request by scoopxyz**
Signed-off-by: Sean Cooper <sean@seancooper.xyz>

### CODE REVIEW

**Comment by scoopxyz** [comment]
The CI is now failing because of its required Python dependencies. @michdolan how do we manage Python dependencies for the CI?

**Comment by scoopxyz** [comment]
> Thanks Sean, this is super helpful!
> 
> I notice that you are deleting the image files used for the baking_luts.rst and spi_vfx.rst pages. I was going to keep both of those pages and so we should keep the images too. Perhaps move them under the tutorials directory for now please (unless I'm misunderstanding what you've done).
> 
> Thanks!!

added back

**Comment by michdolan** [comment]
See my explanation in #1074  on installing Python packages via CMake.

**Comment by scoopxyz** [comment]
Now running into errors, where a lot of python packages don't like have a manual prefix specified by the python macro...

Will need to dig into what's required to work around that

```
Installing collected packages: sphinxcontrib-applehelp, sphinxcontrib-devhelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, MarkupSafe, Jinja2, Pygments, docutils, snowballstemmer, pytz, babel, alabaster, imagesize, chardet, idna, urllib3, certifi, requests, setuptools, pyparsing, six, packaging, sphinx, sphinxemoji, romnnn-sphinx-press-theme
    Running setup.py install for sphinxcontrib-applehelp ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-20f8ufsi/sphinxcontrib-applehelp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-20f8ufsi/sphinxcontrib-applehelp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lhpzn1vh/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fawlty/.local/include/python3.8/sphinxcontrib-applehelp --prefix=/media/fawlty/Alpha/Dev/github/OpenColorIO/build/ext/dist
         cwd: /tmp/pip-install-20f8ufsi/sphinxcontrib-applehelp/
    Complete output (2 lines):
    running install
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-20f8ufsi/sphinxcontrib-applehelp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-20f8ufsi/sphinxcontrib-applehelp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lhpzn1vh/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fawlty/.local/include/python3.8/sphinxcontrib-applehelp --prefix=/media/fawlty/Alpha/Dev/github/OpenColorIO/build/ext/dist Check the logs for full command output.
make[2]: *** [CMakeFiles/romnnn-sphinx-press-theme.dir/build.make:57: romnnn-sphinx-press-theme] Error 1
make[1]: *** [CMakeFiles/Makefile2:804: CMakeFiles/romnnn-sphinx-press-theme.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by scoopxyz** [comment]
https://github.com/pypa/pip/issues/7309

**Comment by scoopxyz** [comment]
Latest is Windows builds failing:
```
Could not import extension recommonmark (exception: No module named 'recommonmark')
```
Leads me to believe we're not populating the windows PYTHONPATH correctly through the `find_python_package` macro.

**Comment by scoopxyz** [comment]
Well... I ended up cheating a bit. Blocking doc generation for Python 2 and Windows. I'm not sure that we'll ever be able to support Python 2, but we can certainly get Windows working in the future, I just don't have a local Windows machine so it's hell to test via CI.
Waiting for second approval then we can merge and focus on getting it working with RTD. Plus I need to add back in sphinx-tabs as I was also having cross-platform build issues with that....

**Pull request merged**
