### PR TITLE
After Effects and Photoshop plug-in updates

### PR DESCRIPTION
**Pull request by fnordware**
Keeping up with OCIO library changes along with some bug fixes, including a fix for Issue #1364.

### CODE REVIEW

**Comment by hodoulp** [comment]
Hi @fnordware,
The TSC approved a v2.0.1 version so I currently push some pull requests from `master` to `RB-2.0`.
This pull request contains the fix around #1364 plus some changes to match the next OpenColorIO version (i.e. 2.1.x). If you want the fix changes to be in `RB-2.0` you need to have them in separate pull request so it can be merged in `RB-2.0`.

**Comment by fnordware** [comment]
Done, @hodoulp!

**Review by hodoulp — APPROVED** [review]

**Comment by hodoulp** [comment]
Hi @fnordware, let us know when the pull request is ready for merge.

**Comment by fnordware** [comment]
It's ready, @hodoulp. Thanks!

**Review by hodoulp — APPROVED** [review]

**Review by doug-walker — APPROVED** [review]

**Pull request merged**
