### PR TITLE
Adsk Contrib - Add preliminary support for ACES Metadata Files (AMF)

### PR DESCRIPTION
**Pull request by doug-walker**
Adds a prototype Python tool named pyocioamf that converts an ACES Metadata File (AMF) into the OCIO native transform format CTF. It uses a prototype ACES Reference config file that is serving as a database of ACES Transform IDs for interpreting the AMF file. An example AMF file was included as well, since they are not very widely available currently.

This is intended as a preliminary first step to explore how to best support AMF in OCIO.

Signed-off-by: Doug Walker <doug.walker@autodesk.com>

### CODE REVIEW

**Comment by hodoulp** [comment]
This pull request is still waiting for some review/approval. Thanks.

**Review by remia — APPROVED** [review]

**Comment by hodoulp** [comment]
Friendly reminder that the pull request can now be merged this week as it's now more than 2 weeks old.

**Comment by remia** [comment]
Just confirming, I tested on my side on it worked as expected when I checked the result against standard ACES pipeline (removing temporarily the LMTs in the AMF). Thanks for the work @doug-walker, for a prototype it will already be really helpful!

**Review by hodoulp — APPROVED** [review]
As the PR is already more than two-weeks old, I approve it.

**Pull request merged**
