### PR TITLE
Add Config working group notes for 11-17-2020

### PR DESCRIPTION
**Pull request by michdolan**
Signed-off-by: Michael Dolan <michdolan@gmail.com>

### CODE REVIEW

**Review by carolalynn22 — APPROVED** [review]
Looks like the spreadsheet needs the viewing perms updated, but these notes look good :)

**Review by KelSolaar — APPROVED** [review]
LGTM!

**Review by doug-walker — APPROVED** [review]

**Review by zachlewis — APPROVED** [review]

**Comment by doug-walker** [comment]
Minor, but Michael you might want to correct the name of the PR to 11-17 rather than 11-20.

**Comment by michdolan** [comment]
Closing and reopening to trigger new CI build.

**Review by zachlewis — APPROVED** [review]

**Pull request merged**
