### PR TITLE
Move fnord files to fnord folder

### PR DESCRIPTION
**Pull request by kingsawyer**
The vendor fnord owns these PhotoShop and AfterEffects plugins. Place in their own directory to allow other plugins for PhotoShop or AfterEffects and not to confuse people with the official Adobe support for OCIO in these products

### CODE REVIEW

**Comment by doug-walker** [comment]
@fnordware, would you please review this PR?

**Comment by fnordware** [comment]
Now that After Effects has native support and it's on the way for Photoshop, maybe we should just delete these plug-ins from the main OpenColorIO repository. They weren't well-integrated with the rest of the repo anyway, relying on Xcode and Visual Studio projects. I'll make a new repo of my own to store them for posterity's sake.

I don't think there will ever be replacement After Effects and Photoshop plug-ins, OCIO will just be built-in.

**Comment by doug-walker** [comment]
That sounds like a sensible plan, given that Adobe is now providing built-in support.

Many thanks for your work on these plug-ins Brendan, I know they've been a huge help to many people over the years!

**Comment by carolalynn** [comment]
Agreed - these plug-ins have saved many a production & color pipeline.
Thank you, Brendan!

**Comment by kingsawyer** [comment]
I will close this then and open a delete PR

**Pull request closed without merging**
