### PR TITLE
Add virtual display python bindings

### LINKED ISSUE #1317: Add missing ICC monitor methods to Python binding
The C++ methods Config::instantiateDisplayFromICCProfile and Config::instantiateDisplayFromMonitorName  are missing in the Python bindings and should be added.

### PR DESCRIPTION
**Pull request by michdolan**
Adds missing Python bindings for OCIO Config virtual display interface.

Fixes #1317

### CODE REVIEW

**Comment by michdolan** [comment]
@meimchu are you still interested in writing tests for these new Python bindings?

**Review by hodoulp — CHANGES_REQUESTED** [review]
LGTM. But I think there should be at least one Python test. Even if that's platform specific you can get some hints from Config_tests.cpp `OCIO_ADD_TEST(Config, virtual_display)` to create something platform agnostic (and postpone the platform specific parts for now).

**Comment by hodoulp** [comment]
**That's a candidate for 2.0.2**

**Review by doug-walker — APPROVED** [review]

**Comment by michdolan** [comment]
Added an implementation of the platform agnostic portion of `OCIO_ADD_TEST(Config, virtual_display)` to the Python tests. In the process I found a few other missing methods around the virtual displays in there and added them.

**Comment by meimchu** [comment]
Thanks @michdolan for pinging me about this. Let me take a look at it for creating python unit tests!

**Comment by michdolan** [comment]
@meimchu I reimplemented a basic test from the C++ unit tests so this can be merged, but as this is a complex feature there is more work to be done in a future PR, specifically testing the platform specific virtual display/system monitor interaction. Examples of that also live in the C++ tests. Thanks for your help!

**Review by hodoulp — APPROVED** [review]

**Comment by remia** [comment]
As mentioned on Slack, should we port this to the RB 2.0 branch? This is currently not available on 2.0.3 but is on 2.1.0 as @doug-walker found.

**Comment by hodoulp** [comment]
The idea around a potential 2.0.3 version is to only bring critical fixes (e.g. color processing errors like in 2.0.2) and suggest users to switch to the latest 2.1 version as soon as possible. At a technical point of view, updating from 2.0.x to 2.0.4 or 2.1.2 should be the same among of work. The point is to put extra attention not increasing too much the number of supported versions. So, I suggest you to bring the topic to the next TSC meeting to agree on a version support policy.

**Comment by remia** [comment]
Thanks @hodoulp, I'll add it to the agenda for the next meeting.

**Pull request merged**
