### PR TITLE
Remove OpenColorIOHeaders target and hardcoded install paths

### PR DESCRIPTION
**Pull request by remia**
Following @lgritz comment in #1397, I think we can remove the `OpenColorIOHeaders` to simplify the CMake scripts a bit. I had some issues with documentation build because I first generated the OpenColorIOABI.h in a new location but resolved this by using the exact same target path as before which I think is the simplest solution.

There shouldn't be a need to merge this for the upcoming release.

### CODE REVIEW

**Review by hodoulp — APPROVED** [review]

**Comment by remia** [comment]
Updated install paths to use CMake automatic variables as suggested in #1296. Also updated public headers installation to use `PUBLIC_HEADER` target property. Using these new variables could update the install folder structure on Windows, while probably being more "as expected".

**Comment by hodoulp** [comment]
@remia Following the last commit, do you need to update the `CMakeLists.txt` from all the `apps`, all the `libutils`, and the `Python` bindings?

**Comment by hodoulp** [comment]
There is also some hard-coded `lib` to change for the `Python bindings` i.e. src/bindings/python/CMakeLists.txt  at line 229 & 231

**Comment by remia** [comment]
Thanks @hodoulp good point, it seems like we should stop using `${LIB_SUFFIX}` according to https://gitlab.kitware.com/cmake/cmake/-/issues/18640#note_488642.

**Review by hodoulp — APPROVED** [review]

**Comment by hodoulp** [comment]
@michdolan The PR is a candidate for `RB-2.1`

**Comment by hodoulp** [comment]
@michdolan or @doug-walker The PR is close to the two-weeks rule, could one of you have a look? Thanks.

**Review by doug-walker — APPROVED** [review]

**Comment by zachlewis** [comment]
Oh whoops -- yep, that's the one I was going for.

**Pull request merged**
